name: Build and publish

on:
  push:
    branches: [ new ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch
      - run: git config --local user.email "loremipsumquaestio@gmail.com"
      - run: git config --local user.name "Mr. Question Mark"
      - run: git switch page
      - run: git merge --no-edit -X theirs --allow-unrelated-histories new
      - run: npm i
      - run: rm -rf docs
      - run: npx parcel build --public-url . --dist-dir docs src/index.html
      - run: git add docs
      - run: git commit -m "v$(cat package.json | jq -r .version), $(date)"
      - run: git push